# Form implementation generated from reading ui file '.\lib\ui\action_view.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_action_view(object):
    def setupUi(self, action_view):
        action_view.setObjectName("action_view")
        action_view.resize(392, 525)
        action_view.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(218, 221, 225);")
        self.verticalLayout = QtWidgets.QVBoxLayout(action_view)
        self.verticalLayout.setObjectName("verticalLayout")
        self.action_option = QtWidgets.QWidget(parent=action_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.action_option.sizePolicy().hasHeightForWidth())
        self.action_option.setSizePolicy(sizePolicy)
        self.action_option.setObjectName("action_option")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.action_option)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_add = QtWidgets.QPushButton(parent=self.action_option)
        self.button_add.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_add.setFont(font)
        self.button_add.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.button_add.setObjectName("button_add")
        self.horizontalLayout_3.addWidget(self.button_add)
        self.button_edit = QtWidgets.QPushButton(parent=self.action_option)
        self.button_edit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_edit.setFont(font)
        self.button_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout_3.addWidget(self.button_edit)
        self.button_delete = QtWidgets.QPushButton(parent=self.action_option)
        self.button_delete.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_delete.setFont(font)
        self.button_delete.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout_3.addWidget(self.button_delete)
        self.verticalLayout.addWidget(self.action_option)
        self.action_field = QtWidgets.QFrame(parent=action_view)
        self.action_field.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.action_field.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.action_field.setObjectName("action_field")
        self.verticalLayout.addWidget(self.action_field)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)

        self.retranslateUi(action_view)
        QtCore.QMetaObject.connectSlotsByName(action_view)

    def retranslateUi(self, action_view):
        _translate = QtCore.QCoreApplication.translate
        action_view.setWindowTitle(_translate("action_view", "Frame"))
        self.button_add.setText(_translate("action_view", "Thêm"))
        self.button_edit.setText(_translate("action_view", "Sửa"))
        self.button_delete.setText(_translate("action_view", "Xóa"))
