# Form implementation generated from reading ui file '.\\lib\ui\confirm_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_confirm_dialog(object):
    def setupUi(self, confirm_dialog):
        confirm_dialog.setObjectName("confirm_dialog")
        confirm_dialog.resize(400, 163)
        self.verticalLayout = QtWidgets.QVBoxLayout(confirm_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=confirm_dialog)
        self.label.setMinimumSize(QtCore.QSize(100, 80))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=confirm_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(confirm_dialog)
        self.buttonBox.accepted.connect(confirm_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(confirm_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(confirm_dialog)

    def retranslateUi(self, confirm_dialog):
        _translate = QtCore.QCoreApplication.translate
        confirm_dialog.setWindowTitle(_translate("confirm_dialog", "Dialog"))
        self.label.setText(_translate("confirm_dialog", "Bạn có chắc chắn muốn xóa ?"))
