# Form implementation generated from reading ui file 'd:\CTARG_Project\Python\may_1\lib\ui\grid_view.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_list_item(object):
    def setupUi(self, list_item):
        list_item.setObjectName("list_item")
        list_item.resize(600, 525)
        list_item.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(218, 221, 225);")
        self.verticalLayout = QtWidgets.QVBoxLayout(list_item)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=list_item)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(parent=list_item)
        font = QtGui.QFont()
        font.setPointSize(4)
        self.line.setFont(font)
        self.line.setStyleSheet("border-color: rgb(103, 103, 103);\n"
"background-color: rgb(79, 79, 79);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(parent=list_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 578, 465))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(list_item)
        QtCore.QMetaObject.connectSlotsByName(list_item)

    def retranslateUi(self, list_item):
        _translate = QtCore.QCoreApplication.translate
        list_item.setWindowTitle(_translate("list_item", "Frame"))
        self.label.setText(_translate("list_item", "Danh sách"))
