# Form implementation generated from reading ui file 'd:\CTARG_Project\Python\may_1\lib\ui\product_card.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_product_card(object):
    def setupUi(self, product_card):
        product_card.setObjectName("product_card")
        product_card.resize(400, 250)
        product_card.setMinimumSize(QtCore.QSize(150, 100))
        product_card.setMaximumSize(QtCore.QSize(400, 250))
        product_card.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"border-color: rgb(255, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(product_card)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=product_card)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.name_label)
        self.name_content = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.name_content.setFont(font)
        self.name_content.setText("")
        self.name_content.setObjectName("name_content")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_content)
        self.price_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.price_label.setFont(font)
        self.price_label.setObjectName("price_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.price_label)
        self.price_content = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.price_content.setFont(font)
        self.price_content.setText("")
        self.price_content.setObjectName("price_content")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.price_content)
        self.descript_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.descript_label.setFont(font)
        self.descript_label.setObjectName("descript_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.descript_label)
        self.descript_content = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.descript_content.setFont(font)
        self.descript_content.setWordWrap(True)
        self.descript_content.setObjectName("descript_content")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.descript_content)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(205, 253, 255);\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(product_card)
        QtCore.QMetaObject.connectSlotsByName(product_card)

    def retranslateUi(self, product_card):
        _translate = QtCore.QCoreApplication.translate
        product_card.setWindowTitle(_translate("product_card", "Frame"))
        self.name_label.setText(_translate("product_card", "Tên sản phẩm"))
        self.price_label.setText(_translate("product_card", "Giá"))
        self.descript_label.setText(_translate("product_card", "Chi tiết"))
        self.descript_content.setText(_translate("product_card", "When you click the button to launch the dialog, you may notice that it appears away from the parent window "))
        self.pushButton.setText(_translate("product_card", "Chọn"))
