# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './lib/ui/prod_line_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_prod_line_detail(object):
    def setupUi(self, prod_line_detail):
        prod_line_detail.setObjectName("prod_line_detail")
        prod_line_detail.resize(400, 68)
        self.horizontalLayout = QtWidgets.QHBoxLayout(prod_line_detail)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prod_name = QtWidgets.QLabel(prod_line_detail)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.prod_name.setFont(font)
        self.prod_name.setText("")
        self.prod_name.setObjectName("prod_name")
        self.horizontalLayout.addWidget(self.prod_name)
        self.prod_quant = QtWidgets.QLabel(prod_line_detail)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.prod_quant.setFont(font)
        self.prod_quant.setText("")
        self.prod_quant.setObjectName("prod_quant")
        self.horizontalLayout.addWidget(self.prod_quant)
        self.result = QtWidgets.QLabel(prod_line_detail)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.horizontalLayout.addWidget(self.result)

        self.retranslateUi(prod_line_detail)
        QtCore.QMetaObject.connectSlotsByName(prod_line_detail)

    def retranslateUi(self, prod_line_detail):
        _translate = QtCore.QCoreApplication.translate
        prod_line_detail.setWindowTitle(_translate("prod_line_detail", "Form"))
